### ISSUE TITLE
Possible Version Mismatch

### ISSUE THREAD

**Issue by bbarrington42** [exercism/typescript-test-runner#37]
Hi,
Tests for simple-cipher are passing for me locally, but failing online. The test runner reports a compilation failure. It's failing on my import statement (the first line of my file):
`import * as crypto from 'crypto';`
The error is:
`simple-cipher.ts(1,25): error TS2307: Cannot find module 'crypto' or its corresponding type declarations.`
Version info:
`node -v
v17.1.0

tsc -v
Version 4.5.2`

Please let me know if you need any more information.

Thanks,
Bill

**Comment by SleeplessByte** [comment]
Hi there. `crypto` is currently not included in the "pre-approved" package list in the test runner. What exercise do you need it for? I'm happy to add it and push a new version :)

**Comment by SleeplessByte** [comment]
Closing because there was no response.
